---
chruby_version: 0.3.8
ruby_install_version: 0.4.3
ruby_version: 2.1
phantomjs_version: 1.9.7
install_xvfb: False
install_firefox: False
install_webkit: False
postgresql_env:
  LC_CTYPE: "{{ locale }}"
  LC_COLLATE: "{{ locale }}"
