---
# Install software to execute tests in headless mode

- name: Install Xvfb and x11vnc
  apt: name={{ item }} state=latest
  with_items:
    - xvfb
    - x11vnc
  when: install_xvfb

- name: Add Xvfb sys-v script
  copy: src=xvfb dest=/etc/init.d/xvfb owner=root group=root mode=0755
  when: install_xvfb

- name: Add Xvfb configuration
  copy: content='export DISPLAY=:1' dest=/etc/profile.d/x-display.sh owner=root group=root mode=0755
  when: install_xvfb

- name: Start Xfvb service
  service: name=xvfb state=started
  when: install_xvfb
